language: java
jdk:
  - oraclejdk8

sudo: false
install: true


before_script:
- ./mvnw install -q -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true || true
- ./mvnw install -q -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true
script: ./mvnw install -q -nsu -Dmaven.test.redirectTestOutputToFile=true -P '!integration'

deploy:
    provider: heroku
    api_key:
        secure: c5f241d8-9490-421e-83f3-6028cc66567e
    on: master
    app: ulyseodev
