language: java
jdk:
  - oraclejdk8

after_success:
- ./gradlew jacocoTestReport coveralls

deploy:
    provider: heroku
    api_key:
        secure: c5f241d8-9490-421e-83f3-6028cc66567e
    on: master
    app: ulyseodev
